export enum RoadTypeEnum {
  Streets = 1,
  Primary_Street = 2,
  FreeWays = 3,
  Ramps = 4,
  Trails = 5,
  Primary = 6,
  Secondary = 7,
  Trails4x4_8 = 8,
  Trails4x4_14 = 14,
  Ferry_Crossing = 15,
  Walkway = 9,
  Pedestrian = 10,
  Exit = 11,
  Stairway = 16,
  Private_Road = 17,
  Railroads = 18,
  Runway_Taxiway = 19,
  Parking_Lot_Road = 20,
  Service_Road = 21,
}
